CREATE PROCEDURE GetKnoDetails
@KNO BIGINT
AS
BEGIN
	SELECT LEFT(KNO,7) OFFICE_CODE,Name,FatherName,KNO,MOBILE_NO,LANDLINENO,EMAIL_ADDRESS,ACCOUNT_NO,ADDRESS1,ADDRESS2,ADDRESS3,LANDMARK,SERVICE_STATUS,
	FEEDER_NAME,AREA_CODE
	FROM CONSUMER WHERE KNO=@KNO
END