CREATE PROCEDURE CALL_Queue_Abandon_Insert
@Date1 Datetime,
@Total_Calls_Offered BIGINT,
@Total_Calls_Answered BIGINT,
@Short_Calls BIGINT,
@Ans_LessThan_5_Secs BIGINT,
@Ans_6to10_Secs BIGINT,
@Ans_11to20_Secs BIGINT,
@Ans_21to30_Secs BIGINT,
@Ans_31to40_Secs BIGINT,
@Ans_41to50_Secs BIGINT,
@Ans_51to60_Secs BIGINT,
@Ans_GreaterThan_60_Secs BIGINT,
@Total_Calls_Abandon BIGINT,
@Aban_LessThan5_Sec BIGINT,
@Aban_6to10_Secs BIGINT,
@Aban_11to20_Secs BIGINT,
@Aban_21to30_Secs BIGINT,
@Aban_31to40_Secs BIGINT,
@Aban_41to50_Secs BIGINT,
@Aban_51to60_Secs BIGINT,
@Aban_GreaterThan_60_Secs BIGINT,
@Failed BIGINT,
@Total_Call_Handling_Time NVARCHAR(50),
@Total_Talk_Time NVARCHAR(50),
@Average_Talk_Time NVARCHAR(50),
@Average_Call_Handling_Time NVARCHAR(50),
@Calls_Held BIGINT,
@Calls_Queued BIGINT,
@Calls_Queue_Time NVARCHAR(50),
@Avg_Queue_Time NVARCHAR(50),
@Service_per DECIMAL(18,2),
@Aban_Per DECIMAL(18,2),
@SLA_Per DECIMAL(18,2),
@ABN_10_Sec BIGINT,
@ABN_10_Sec_Per DECIMAL(18,2),
@ABN_20_Sec BIGINT,
@ABN_20_Sec_Per DECIMAL(18,2),
@ABN_30_Sec BIGINT,
@ABN_30_Sec_Per DECIMAL(18,2),
@ABN_60_Sec BIGINT,
@ABN_60_Sec_Per DECIMAL(18,2),
@ABN_90_Sec BIGINT,
@ABN_90_Sec_Per DECIMAL(18,2),
@SLA_10_Sec BIGINT,
@SLA_10_Sec_Per DECIMAL(18,2),
@SLA_20_Sec BIGINT,
@SLA_20_Sec_Per DECIMAL(18,2),
@SLA_30_Sec BIGINT,
@SLA_30_Sec_Per DECIMAL(18,2),
@SLA_60_Sec BIGINT,
@SLA_60_Sec_Per DECIMAL(18,2),
@SLA_90_Sec BIGINT,
@SLA_90_Sec_Per DECIMAL(18,2),
@Total_Hold_Time NVARCHAR(50),
@Avg_Hold_Time_of_Ans NVARCHAR(50),
@Total_Wrapup_Time NVARCHAR(50),
@Avg_Wrapup_Time NVARCHAR(50),
@retStatus   INT OUTPUT,
@retMsg   VARCHAR (255) OUTPUT
AS
BEGIN
 INSERT INTO CALL_Queue_Abandon
 VALUES(convert(date,@Date1),@Total_Calls_Offered,@Total_Calls_Answered,@Short_Calls,@Ans_LessThan_5_Secs,@Ans_6to10_Secs,@Ans_11to20_Secs,@Ans_21to30_Secs,
@Ans_31to40_Secs,@Ans_41to50_Secs,@Ans_51to60_Secs,@Ans_GreaterThan_60_Secs,@Total_Calls_Abandon,@Aban_LessThan5_Sec,@Aban_6to10_Secs,@Aban_11to20_Secs,
@Aban_21to30_Secs,@Aban_31to40_Secs,@Aban_41to50_Secs,@Aban_51to60_Secs,@Aban_GreaterThan_60_Secs,@Failed,@Total_Call_Handling_Time,@Total_Talk_Time,
@Average_Talk_Time,@Average_Call_Handling_Time,@Calls_Held,@Calls_Queued,@Calls_Queue_Time,@Avg_Queue_Time,@Service_per,@Aban_Per,@SLA_Per,@ABN_10_Sec,
@ABN_10_Sec_Per,@ABN_20_Sec,@ABN_20_Sec_Per,@ABN_30_Sec,@ABN_30_Sec_Per,@ABN_60_Sec,@ABN_60_Sec_Per,@ABN_90_Sec,@ABN_90_Sec_Per,@SLA_10_Sec,@SLA_10_Sec_Per,
@SLA_20_Sec,@SLA_20_Sec_Per,@SLA_30_Sec,@SLA_30_Sec_Per,@SLA_60_Sec,@SLA_60_Sec_Per,@SLA_90_Sec,@SLA_90_Sec_Per,@Total_Hold_Time,@Avg_Hold_Time_of_Ans,
@Total_Wrapup_Time,@Avg_Wrapup_Time,1,0,GETDATE())
SELECT @retStatus = 1 , @retMsg='Remark Saved';
END