USE [CALL_CENTER_NEW]
GO

/****** Object:  Table [dbo].[MST_USERS]    Script Date: 01-04-2023 14:21:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MST_USERS_API](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_NAME] [varchar](255) NULL,
	[PASSWORD] [varchar](255) NULL,
	[IS_ACTIVE] [bit] NULL,
	[TIME_STAMP] [datetime] NULL,
 CONSTRAINT [PK_MST_USERS_API] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



