 CREATE PROCEDURE SearchComplaintByKNo
@KNO VARCHAR(15)
AS
BEGIN
	SELECT A.OFFICE_CODE,B.COMPLAINT_TYPE,A.COMPLAINT_NO,A.NAME,A.FATHER_NAME,A.KNO,A.LANDLINE_NO,C.SOURCE_NAME,A.MOBILE_NO,A.ALTERNATE_MOBILE_NO,ISNULL(A.ADDRESS1,'')+' '+ISNULL(A.ADDRESS2,'')+' '+ISNULL(A.ADDRESS3,'')+' '+ISNULL(A.LANDMARK,'') ADDRESS
	FROM COMPLAINT(NOLOCK) A
	LEFT OUTER JOIN MST_COMPLAINT_TYPE(NOLOCK) B ON A.COMPLAINT_TYPE=B.ID
	LEFT OUTER JOIN MST_COMPLAINT_SOURCE(NOLOCK) C ON A.COMPLAINT_SOURCE_ID=C.ID
	WHERE KNO=@KNO
END

 CREATE PROCEDURE SearchComplaintByComplaintNo
@Complaint_NO VARCHAR(15)
AS
BEGIN
	SELECT A.OFFICE_CODE,B.COMPLAINT_TYPE,A.COMPLAINT_NO,A.NAME,A.FATHER_NAME,A.KNO,A.LANDLINE_NO,C.SOURCE_NAME,A.MOBILE_NO,A.ALTERNATE_MOBILE_NO,ISNULL(A.ADDRESS1,'')+' '+ISNULL(A.ADDRESS2,'')+' '+ISNULL(A.ADDRESS3,'')+' '+ISNULL(A.LANDMARK,'') ADDRESS
	FROM COMPLAINT(NOLOCK) A
	LEFT OUTER JOIN MST_COMPLAINT_TYPE(NOLOCK) B ON A.COMPLAINT_TYPE=B.ID
	LEFT OUTER JOIN MST_COMPLAINT_SOURCE(NOLOCK) C ON A.COMPLAINT_SOURCE_ID=C.ID
	WHERE COMPLAINT_NO=@Complaint_NO
END